### ISSUE TITLE
Edge Browser missing in BrowserManagement.createDesiredCapabilities()?

### ISSUE THREAD

**Issue by hleskien** [Hi-Fi/robotframework-seleniumlibrary-java#28]
Hi,
I'm trying to write a Robot Framework test for an application frontend that supports the Edge browser. When I try to:
Open Browser    ${URL}    edge    none    ${SELENIUM_HUB}

I finally get:
"com.github.markusbernhardt.seleniumlibrary.SeleniumLibraryFatalException: edge is not a supported browser."

I'm using release 3.7.1.1 and found out that there is even no communication with the Selenium Grid server. So I was wondering what is going on and was digging in the source code a little bit. I believe that the Edge browser is missing in the method BrowserManagement.createDesiredCapabilities(). Am I right?

If not, maybe you can help to get my setup going?
Thank you in advance!

**Comment by Hi-Fi** [comment]
Browser management defines supported browsers, and in this case the method is at https://github.com/Hi-Fi/robotframework-seleniumlibrary-java/blob/master/src/main/java/com/github/markusbernhardt/seleniumlibrary/keywords/BrowserManagement.java#L682. So it seems that edge support was added only for local webdrivers, not remote ones.

I can check the fix for that.

**Comment by Hi-Fi** [comment]
Currently fixed and released at 3.7.1.2-SNAPSHOT. Will be included to next full release, which would be either 3.7.1.2 or 3.8.1.0 (depending on jBrowser). Release should be available later today.

**Comment by hleskien** [comment]
Thank you very much! Will test as soon as possible.

**Comment by hleskien** [comment]
It works!
