### ISSUE TITLE
Input Text shows Russian characters as question marks in a report

### ISSUE THREAD

**Issue by php-coder** [Hi-Fi/robotframework-seleniumlibrary-java#92]
When I use `Input Text` with Russian letters, they are displayed as question marks in a report. It has been reported as https://github.com/MarkusBernhardt/robotframework-selenium2library-java/issues/90 but it's reproduced on 3.141.59.2653

**Comment by Hi-Fi** [comment]
That's clearly encoding error, but would need some inspection if that error is at the library or at RF/Jython side.

I think this is also a good place to start making static HTMLs for tests, so there's no need to rely on outside web pages at least on Travis tests.

**Comment by Hi-Fi** [comment]
Changing logging to use purely Java solution (so not writing things with RF own logger (directly)) seems to be fixing the issue, but not sure if it introduces some other issues (because I have made other libraries with Java logging long time ago, and can't remember now why this was left with the other way).
